### ISSUE TITLE
Feld price_unit statt  list_price verwenden um Multivariants Produkte nutzen zu können

### ISSUE THREAD

**Issue by EmJay276** [fau-fablab/FabLabKasse#78]
Bisher wird bei einem Multivariants Produkt der Sale Price Extra (price_extra) im Kassenterminal nicht beachtet, dadurch ist es nicht möglich Multivariants Produkte mit unterschiedlichen Preisen zu erzeugen. Es wird das Feld Verkaufspreis (list_price) verwendet.

Bei Angebotsanfragen für den Verkauf (und Einkauf!) verwendet das ERP das Feld Preis/ME (price_unit) welches den Sale Price Extra (price_extra) bzw. den Cost Price Extra (cost_price_extra) aus dem Product Template richtig beachtet.

Achtung, es gibt in jedem Produkt (product.product) anscheinend auch ein Feld Varianten-Aufpreis (price_extra) und Purchase Extra Cost (cost_price_extra) welches nur sichtbar ist, wenn man in dem Benutzer das Zugriffsrecht "Produktvarianten (nicht unterstützt)" setzt.

Die richtigen Felder sollten unter "product.variant.dimension.value" im zum Produkt gehörigen Variant zu finden sein, aber keine Gewähr. In der Testdatenbank haben die Produkte mit ID 5009 und 5011 die entsprechenden Felder gesetzt.

Bilder:
![erp_benutzer](https://cloud.githubusercontent.com/assets/8619525/9820709/e9b19750-58b5-11e5-8a42-8020313d22e1.png)
![erp_produkt](https://cloud.githubusercontent.com/assets/8619525/9820708/e9b142e6-58b5-11e5-80ad-104a0c9f88d8.png)
![erp_template](https://cloud.githubusercontent.com/assets/8619525/9820710/e9b3c71e-58b5-11e5-9948-27641f8b761c.png)
![erp_verkauf](https://cloud.githubusercontent.com/assets/8619525/9820711/e9b59c06-58b5-11e5-8809-afafcd83c64c.png)

**Comment by patkan** [comment]
Did just some research with @EmJay276
The product-objects have a property `list_price`, which is used atm.
It seems like this is not the proper one. The ERP calculates the real list price from `list_price`, however then writes this price to the property `lst_price`
I checked the test database: Zero products have a `lst_price` smaller than `list_price`, for most of the products it is the same and only the multi-variants have a `lst_price` that is greater than `list_price`.

Therefore, I think it should be safe to use `lst_price` instead of `list_price`.
